# Generated by Django 5.2.7 on 2025-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_order_discount_amount_order_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество дней аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды'),
        ),
    ]
